# Generated by Django 5.1 on 2024-09-03 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profileImages', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
